### PR TITLE
#393 Translate German comments

### PR DESCRIPTION
**Pull request by tmrpavan**
Translate German comments in NodeNotFoundException File.

Translate German comments to English in  core/src/main/java/de/muenchen/allg/itd51/wollmux/config/NodeNotFoundException.java File.

### CODE REVIEW

**Comment by deneb-alpha** [comment]
@smehrbrodt I had a look at the PR and in general it LGTM. 

I'm just wondering how it will work with the changes to the copyright year. In 2023 we had the transition of the project from LHM to TDF, but I have no idea how this should be reflected in the headers.

**Comment by thorstenb** [comment]
Yeah, the copyright change does not make sense as-is (the copyright of contributed changes is no longer with the city of Munich). A new, extra line would serve the purpose, reading something like:

Copyright © 2022-2023 LibreOffice contributors. All rights reserved.

But since the change history is clear from the git log, nowadays there's not that much need for such header lines in the first place. It also adds a lot of noise to the history, if one needs to update the copyright year constantly.

**Comment by tmrpavan** [comment]
@deneb-alpha 

I was encountered with some build issue to fix that i follow the below instructions from readme file. Let me if i need to make any changes.

Build errors
There are files with header to update: Some of the source files don't have a license header. The header can be updated with:
mvn license:update-file-header

**Comment by thorstenb** [comment]
We might want to get rid of / update to mycila version / disable year updates for the license-maven-plugin.

For the moment, there's at least https://github.com/LibreOffice/WollMux/pull/438 to get LibreOffice contributors properly credited.

**Comment by deneb-alpha** [comment]
@thorstenb sorry for the late reply, I'm sick. 

No concerns with the update itself. Feel free to handle the copyright change as you prefer. 
I agree, probably it makes sense to update in this PR the translations and leave the credits fixes in #438

**Comment by smehrbrodt** [comment]
Can you please resolve the conflicts? Then this can be merged.

**Pull request merged**
